config/routes.rb
Rails.application.routes.draw do
  root "nazokakes#index"
  resources :users

  resources :posts, only: [:new, :create, :index]
  resources :nazokakes, only: [:index]
  resources :questions, only: [:new, :create]
  resources :answers, only: [:new, :create]
  resources :hearts, only: [:new, :create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :questions
  has_many :answers
  has_many :hearts

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @answer = current_user.answers.new(answer_params)
    if @answer.save
      redirect_to posts_path, success: 'Answer was successfully created.'
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :error

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  def new
    @heart = Heart.new
  end

  def create
    @heart = current_user.hearts.new(heart_params)
    if @heart.save
      redirect_to posts_path, success: 'Heart was successfully created.'
    else
      render :new
    end
  end

  private

  def heart_params
    params.require(:heart).permit(:content)
  end
end

app/controllers/nazokakes_controller.rb
class NazokakesController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    @question = Question.random
    @answer = Answer.random
    @heart = Heart.random

    tweet_content = "**ランダムなぞかけ**\n\n【#{@question.content}】とかけて\n【#{@answer.content}】と解く\nその心は、どちらも【#{@heart.content}】\n#かかってる #なぞかけ\n\nkakatteru.onrender.com"
    @encoded_text = URI.encode_www_form_component(tweet_content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    @questions = Question.all
    @answers = Answer.all
    @hearts = Heart.all
    @posts = (@questions + @answers + @hearts).sort_by(&:created_at).reverse!
  end

  def new
    @question = current_user.questions.build
    @answer = current_user.answers.build
    @heart = current_user.hearts.build
  end

  def create
    model_class = [Question, Answer, Heart].find { |m| params.key?(m.name.underscore) }
    @post = current_user.send(model_class.name.underscore.pluralize).new(post_params(model_class))

    if @post.save
      redirect_to posts_path, notice: "#{model_class.name} was successfully created."
    else
      render :new
    end
  end

  private

  def post_params(model_class)
    params.require(model_class.name.underscore.to_sym).permit(:content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to posts_path, success: 'Question was successfully created.'
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: [:index, :new, :create] # this should only be used if you are allowing users to register themselves.
  before_action :check_user, only: %i[edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to posts_path, notice: "User was successfully created." }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_user
      redirect_to(root_url, alert: "Unauthorized access!") unless @user == current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/nazokakes_helper.rb
module NazokakesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def translate_class_name(class_name)
    case class_name
    when "Question"
      "問"
    when "Answer"
      "解"
    when "Heart"
      "心"
    else
      "不明なタイプ"
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="winter">
  <head>
    <title>Kakatteru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>

    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>

    <%= render 'shared/flash_message' %>

    <%= yield %>

  </body>
</html>

app/views/shared/_before_login_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <a class="btn btn-ghost text-xl">かかってる？</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li>
        <%= link_to "ランダム生成", nazokakes_path %>
      </li>
      <li>
        <%= link_to "投稿一覧", posts_path %>
      </li>
      <li>
        <%= link_to "新規登録", new_user_path %>
      </li>
      <li>
        <%= link_to "ログイン", login_path %>
      </li>

    </ul>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to "かかってる？", root_path, class: "btn btn-ghost text-xl" %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li>
        <%= link_to "ランダム生成", nazokakes_path %>
      </li>
      <li>
        <%= link_to "新規投稿", new_post_path %>
      </li>
      <li>
        <%= link_to "投稿一覧", posts_path %>
      </li>
      <li>
        <%= link_to current_user.name, edit_user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %>
      </li>

    </ul>
  </div>
</div>