config/routes.rb
Rails.application.routes.draw do
  root "nazokakes#index"
  resources :users

  resources :posts, only: [:new, :create, :index]
  resources :nazokakes, only: [:index]
  resources :questions, only: [:new, :create]
  resources :answers, only: [:new, :create]
  resources :hearts, only: [:new, :create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.random
    order(Arel.sql('RANDOM()')).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :questions
  has_many :answers
  has_many :hearts

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @answer = current_user.answers.new(answer_params)
    if @answer.save
      redirect_to posts_path, success: 'Answer was successfully created.'
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :error

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  def new
    @heart = Heart.new
  end

  def create
    @heart = current_user.hearts.new(heart_params)
    if @heart.save
      redirect_to posts_path, success: 'Heart was successfully created.'
    else
      render :new
    end
  end

  private

  def heart_params
    params.require(:heart).permit(:content)
  end
end

app/controllers/nazokakes_controller.rb
class NazokakesController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    @question = Question.random
    @answer = Answer.random
    @heart = Heart.random

    tweet_content = "**ランダムなぞかけ**\n\n【#{@question.content}】とかけて\n【#{@answer.content}】と解く\nその心は、どちらも【#{@heart.content}】\n#かかってる #なぞかけ\n\nkakatteru.onrender.com"
    @encoded_text = URI.encode_www_form_component(tweet_content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    @questions = Question.all
    @answers = Answer.all
    @hearts = Heart.all
    @posts = (@questions + @answers + @hearts).sort_by(&:created_at).reverse!
  end

  def new
    @question = current_user.questions.build
    @answer = current_user.answers.build
    @heart = current_user.hearts.build
  end

  def create
    model_class = [Question, Answer, Heart].find { |m| params.key?(m.name.underscore) }
    @post = current_user.send(model_class.name.underscore.pluralize).new(post_params(model_class))

    if @post.save
      redirect_to posts_path, notice: "#{model_class.name} was successfully created."
    else
      render :new
    end
  end

  private

  def post_params(model_class)
    params.require(model_class.name.underscore.to_sym).permit(:content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to posts_path, success: 'Question was successfully created.'
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: 'Login successful'
    else
      flash.now[:error] = 'Login failed'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, error: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: [:index, :new, :create] # this should only be used if you are allowing users to register themselves.
  before_action :check_user, only: %i[edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to posts_path, notice: "User was successfully created." }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_user
      redirect_to(root_url, alert: "Unauthorized access!") unless @user == current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/nazokakes_helper.rb
module NazokakesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def translate_class_name(class_name)
    case class_name
    when "Question"
      "問"
    when "Answer"
      "解"
    when "Heart"
      "心"
    else
      "不明なタイプ"
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %>prohibited this answer from being saved:</h2>
      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_area :content, class: "my-3 textarea textarea-bordered flex w-full items-center gap-2" %>
    <p>と解く</p>
  </div>

  <div class="mt-10 btn btn-primary flex w-full justify-center rounded-md">
    <%= form.submit "解を投稿" %>
  </div>
<% end %>

app/views/hearts/_form.html.erb
<%= form_with(model: heart, local: true) do |form| %>
  <% if heart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(heart.errors.count, "error") %>prohibited this heart from being saved:</h2>
      <ul>
        <% heart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p>その心は、どちらも</p>
    <%= form.text_area :content, class: "my-3 textarea textarea-bordered flex w-full items-center gap-2" %>
  </div>

  <div class="mt-10 btn btn-primary flex w-full justify-center rounded-md">
    <%= form.submit "心を投稿" %>
  </div>
<% end %>

app/views/nazokakes/index.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="my-1 text-center text-2xl font-bold leading-9 text-gray-900">ランダムなぞかけ</h1>
  </div>

  <div class="my-3 card w-full bg-base-100 shadow-xl">

    <div class="m-10 text-center justify-center">
      <% if @question && @answer && @heart %>
        <div class="m-3 flex text-center justify-center">
          <div class="m-3">
            <strong><%= @question.content %></strong>
          </div>
          <div class="m-3 text-gray-400">
            とかけて
          </div>
        </div>

        <div class="m-3 flex text-center justify-center">
          <div class="m-3">
            <strong><%= @answer.content %></strong>
          </div>
          <div class="m-3 text-gray-400">
            と解く
          </div>
        </div>

        <div class="m-3 flex text-center justify-center">
          <div class="m-3 text-gray-400">
            その心は、どちらも
          </div>
          <div class="m-3">
            <strong><%= @heart.content %></strong>
          </div>
        </div>

      <% else %>
        <p>なぞかけの要素が足りません。</p>
      <% end %>

      <div class="actions">
        <%= link_to 'ランダム生成', nazokakes_path, class: "m-5 btn btn-primary btn-wide" %>
      </div>

    <div class="m-3 flex text-center justify-center">
      <div class="actions">
        <%= link_to "Twitterで共有する", "https://twitter.com/intent/tweet?text=#{@encoded_text}", target: "_blank", class: "m-2 btn btn-outline btn-info btn-wide" %>
      </div>

      <div class="actions">
        <%= link_to '投稿してみる', new_post_path, class: "m-2 btn btn-outline btn-secondary btn-wide" %>
      </div>
    </div>
    </div>
  </div>

</div>

app/views/posts/index.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="my-1 text-center text-2xl font-bold leading-9 text-gray-900">投稿一覧</h1>
  </div>

  <ul>
    <% @posts.each do |post| %>
      <div class="my-3 card w-full bg-base-100 shadow-xl">
        <div class="card-body">
          <li class="flex items-center">
            <div class="card-title mx-5 my-1 text-violet-400">
              <%= translate_class_name(post.class.name) %>
            </div>

            <% if post.class.name == "Heart" %>
              <div class="mr-3 my-1 text-gray-400">
                その心は、どちらも
              </div>
            <% end %>

            <div class="mr-3 my-1">
              <strong><%= post.content %></strong>
            </div>
            <div class="text-gray-400">
              <%= case post.class.name
                  when "Question"
                    "とかけて"
                  when "Answer"
                    "と解く"
                  when "Heart"
                    ""
                  else
                    ""
                  end %>
            </div>

            <div class="ml-auto text-sm text-indigo-500">
              投稿者: <%= post.user.name %>
            </div>

          </li>
        </div>
      </div>
    <% end %>
  </ul>

</div>

app/views/posts/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="my-10 text-center text-2xl font-bold leading-9 text-gray-900">新規投稿</h1>
  </div>

<div role="tablist" class="mt-3 tabs tabs-boxed tabs-lg">
  <!-- Question Tab -->
  <input type="radio" id="question_tab" name="post_tabs" role="tab" class="tab" aria-controls="question_content" aria-label="問" checked />

  <div role="tabpanel" id="question_content" class="tab-content p-10">
    <%= render 'questions/form', question: @question %>
  </div>

  <!-- Answer Tab -->
  <input type="radio" id="answer_tab" name="post_tabs" role="tab" class="tab" aria-controls="answer_content" aria-label="解" />
  <div role="tabpanel" id="answer_content" class="tab-content p-10">
    <%= render 'answers/form', answer: @answer %>
  </div>

  <!-- Heart Tab -->
  <input type="radio" id="heart_tab" name="post_tabs" role="tab" class="tab" aria-controls="heart_content" aria-label="心" />
  <div role="tabpanel" id="heart_content" class="tab-content p-10">
    <%= render 'hearts/form', heart: @heart %>
  </div>
</div>

</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %>prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_area :content, class: "my-3 textarea textarea-bordered flex w-full items-center gap-2" %>
    <p>とかけて</p>
  </div>

  <div class="mt-10 btn btn-primary flex w-full justify-center rounded-md">
    <%= form.submit "問を投稿" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<div class="flex flex-col w-full border-opacity-50">

  <%= form_with url: login_path, method: :post do |f| %>
    <div>
      <%= f.label :email, "メールアドレス", class: "my-3 flex w-full items-center gap-2" %>
      <%= f.text_field :email, class: "my-3 input input-bordered flex w-full items-center gap-2"  %>
    </div>

    <div>
      <%= f.label :password, "パスワード", class: "my-3 flex w-full items-center gap-2" %>
      <%= f.password_field :password, class: "my-3 input input-bordered flex w-full items-center gap-2"  %>
    </div>

    <div class="mt-3 btn btn-primary flex w-full justify-center rounded-md">
      <%= f.submit "ログイン" %>
    </div>
  <% end %>

</div>

app/views/user_sessions/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="mt-10 text-center text-2xl font-bold leading-9 text-gray-900">ログイン</h1>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render 'form' %>
  </div>

</div>

app/views/users/_form.html.erb
<div class="flex flex-col w-full border-opacity-50">

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "ユーザー名", style: "display: block", class: "my-3 flex items-center gap-2" %>
    <%= form.text_field :name, class: "my-3 input input-bordered flex w-full items-center gap-2" %>
  </div>

  <div>
    <%= form.label :email, "メールアドレス", style: "display: block", class: "my-3 flex items-center gap-2" %>
    <%= form.text_field :email, class: "my-3 input input-bordered flex w-full items-center gap-2" %>
  </div>

  <div>
    <%= form.label :password, "パスワード", class: "my-3 flex items-center gap-2" %>
    <%= form.password_field :password, class: "my-3 input input-bordered flex w-full items-center gap-2" %>
  </div>

  <div>
    <%= form.label :password_confirmation, "パスワード確認", class: "my-3 flex items-center gap-2" %>
    <%= form.password_field :password_confirmation, class: "my-3 input input-bordered flex w-full items-center gap-2" %>
  </div>

  <div>
    <%= form.submit "登録", class: "mt-3 btn btn-primary flex w-full justify-center rounded-md" %>
  </div>
<% end %>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-3 flex items-center gap-2">
    <div class="my-3 flex items-center gap-2">
      <strong>ユーザー名</strong>
      <%= user.name %>
    </div>
    <div class="my-3 flex items-center gap-2">
      <strong>メールアドレス</strong>
      <%= user.email %>
    </div>
  </p>
</div>

app/views/users/edit.html.erb
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="mt-10 text-center text-2xl font-bold leading-9 text-gray-900">ユーザー編集</h1>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render "form", user: @user %>
  </div>

<br>

  <div class="flex mt-3 sm:mx-auto sm:w-full sm:max-w-sm">
    <div class="mr-3 btn btn-outline btn-primary flex-auto w-full justify-center rounded-md">
      <%= link_to "ユーザー詳細", user_path(@user) %>
    </div>
    <div class="ml-3 btn btn-outline btn-primary flex-auto w-full justify-center rounded-md">
      <%= link_to "ユーザー一覧", users_path %>
    </div>
  </div>

  <div class="mt-3 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= button_to "ユーザー削除", @user, method: :delete, class: "mt-3 btn btn-accent flex w-full justify-center rounded-md" %>
  </div>

app/views/users/index.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="my-1 text-center text-2xl font-bold leading-9 text-gray-900">ユーザー一覧</h1>
  </div>

  <div id="users">
    <% @users.each do |user| %>
      <div class="my-3 card w-full bg-base-100 shadow-xl">
        <div class="card-body">
          <div class="flex items-center justify-between"> <!-- Flexbox container -->
            <div>
              <%= render user %>
            </div>

            <div>
              <%= link_to "詳細", user, class: "btn btn-primary " %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h1 class="mt-10 text-center text-2xl font-bold leading-9 text-gray-900">新規登録</h1>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render "form", user: @user %>
  </div>

</div>

app/views/users/show.html.erb
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render @user %>
  </div>

  <div class="flex mt-3 sm:mx-auto sm:w-full sm:max-w-sm">
    <div class="mr-3 btn btn-outline btn-primary flex-auto w-full justify-center rounded-md">
      <%= link_to "ユーザー編集", edit_user_path(@user) %>
    </div>
    <div class="ml-3 btn btn-outline btn-primary flex-auto w-full justify-center rounded-md">
      <%= link_to "ユーザー一覧", users_path %>
    </div>
  </div>